/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import ThuVien.*;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author DIENMAYXANH
 */
public class Test_frm extends javax.swing.JFrame {

    public Test_frm() {
        initComponents();
        show_Sach();
    }
    
    public KetNoi kn = new KetNoi();
    
    public ArrayList<Test> sachList(){
        ArrayList<Test> sachList = new ArrayList<>();
        try {
        Connection con = kn.getConnection();
        String query1 = "SELECT * FROM Test2";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query1);
        Test test;
        while(rs.next()){
            test = new Test(rs.getString("Masach"), rs.getString("Tensach"),rs.getString("Tacgia"));
            sachList.add(test);
        }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        return sachList;
    }
    
    public void show_Sach(){ //Hàm hiển thị bảng từ SQL ra màn hình
        //tblTest.fixTable(jScrollPane1);
        ArrayList<Test> list = sachList();
        DefaultTableModel model = (DefaultTableModel) tblTest.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {
            row[0] = tblTest.getRowCount() + 1;
            row[1] = list.get(i).getMasach();
            row[2] = list.get(i).getTensach();
            row[3] = list.get(i).getTacgia();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTest = new javax.swing.JTable();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ss = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Masach", "Tên sách", "Tác giả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTest.setToolTipText("Bảng thông tin Sách");
        tblTest.setShowHorizontalLines(true);
        tblTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTestMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblTest);

        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt1KeyReleased(evt);
            }
        });

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tên sách");

        jLabel2.setText("Tác giả");

        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ss.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ss.setText(" ");

        jTextField1.setEditable(false);
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(332, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(137, 137, 137))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        Connection con = kn.getConnection();
        String query = "insert into Test2(Tensach, Tacgia) values (?,?)";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, txt1.getText());
        ps.setString(2, txt2.getText());
        ps.executeUpdate();//Update dữ liệu đã nhâp lên SQL
        //3 dòng sau để sau khi update xong thì bảng cũng sẽ tự cập nhật lại mà kh cần chạy lại phần mềm
        DefaultTableModel model = (DefaultTableModel) tblTest.getModel();
        model.setRowCount(0);
        show_Sach();
        JOptionPane.showMessageDialog(this, "Thêm dữ liệu thành công");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
        txt1.setText(null);
        txt2.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(tblTest.getSelectedRow()== -1){
            JOptionPane.showMessageDialog(this, "Hhaha", "Thong bao", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int xn = JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa dữ liệu không?", "Xoá", JOptionPane.YES_NO_OPTION);
        if(xn==0){
        try {
        Connection con = kn.getConnection();
        int row = tblTest.getSelectedRow(); //Trả về dữ liệu của dòng đang được chọn
        String value = (tblTest.getModel().getValueAt(row, 1).toString());
        String query = "DELETE FROM Test2 WHERE Masach= '"+value+"'";
        PreparedStatement ps = con.prepareStatement(query);
        ps.executeUpdate(); //Update dữ liệu lên SQL
        //3 dòng sau để sau khi xóa xong thì bảng cũng sẽ tự cập nhật lại mà kh cần chạy lại phần mềm
        DefaultTableModel model = (DefaultTableModel) tblTest.getModel();
        model.setRowCount(0);
        show_Sach();
        JOptionPane.showMessageDialog(this, "Xoá dữ liệu thành công");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblTestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTestMousePressed
        // TODO add your handling code here:
        int i = tblTest.getSelectedRow();
        TableModel model = tblTest.getModel();
        
        txt1.setText(model.getValueAt(i, 2).toString());
        txt2.setText(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_tblTestMousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(tblTest.getRowCount()==17){
            JOptionPane.showMessageDialog(this, "Vải", "uk", HEIGHT);
            return;
        }
        int xn = JOptionPane.showConfirmDialog(this,"Bạn có muốn sửa dữ liệu không?", "Sửa", JOptionPane.YES_NO_OPTION);
        if(xn==0){
        try {
        Connection con = kn.getConnection();
        int row = tblTest.getSelectedRow();
        String value = (tblTest.getModel().getValueAt(row, 1).toString());
        String query = "UPDATE Test2 SET Tensach=?, Tacgia=? where Masach = '"+value+"'";
        PreparedStatement ps = con.prepareStatement(query);
        ps.setString(1, txt1.getText());
        ps.setString(2, txt2.getText());
        ps.executeUpdate();//Update dữ liệu SQL
        //3 dòng sau để sau khi update xong thì bảng cũng sẽ tự cập nhật lại mà kh cần chạy lại phần mềm
        DefaultTableModel model = (DefaultTableModel) tblTest.getModel();
        model.setRowCount(0);
        show_Sach();
        JOptionPane.showMessageDialog(this, "Sửa dữ liệu thành công");
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyReleased
        // TODO add your handling code here:
        if(!(Pattern.matches("\"^[a-zA-Z'-'\\sáàảãạăâắằấầặẵẫậéèẻ ẽẹếềểễệóòỏõọôốồổỗộ ơớờởỡợíìỉĩịđùúủũụưứ� �ửữựÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠ ƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼ� ��ỀỂỄỆỈỊỌỎỐỒỔỖỘỚỜỞ ỠỢỤỨỪỬỮỰỲỴÝỶỸửữựỵ ỷỹ]*$\"", txt1.getText()))){
            ss.setText("!");
        }else{
            ss.setText("");
        }
    }//GEN-LAST:event_txt1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            
            UIManager.put("ScrollPane.border", new Color(255,255,255));
            UIManager.put("TextComponent.arc", 15);
            UIManager.put( "Component.focusWidth", 0);
            UIManager.put("Button.arc", 15);
            UIManager.setLookAndFeel(new FlatMacLightLaf());
        } catch (Exception e) {
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test_frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel ss;
    private javax.swing.JTable tblTest;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    // End of variables declaration//GEN-END:variables
}
